wandb_version: 1

log:
  desc: null
  value: true
seed:
  desc: null
  value: 42
log_dir:
  desc: null
  value: ./logs
save_dir:
  desc: null
  value: ./models
adversary_episode_length:
  desc: null
  value: 10
num_eval_episodes:
  desc: null
  value: 25
learning_rate:
  desc: null
  value: 0.1
discount_factor:
  desc: null
  value: 0.99
epsilon:
  desc: null
  value: 0.05
num_q_learning_episodes:
  desc: null
  value: 100
init_scale:
  desc: null
  value: 0.01
ppo_train_steps:
  desc: null
  value: 10000
num_policy_eval_episodes:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702321312.367429
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.16.0
      8:
      - 4
      - 5
      13: darwin-arm64
